# -*- coding: utf-8 -*-
"""TEXT_AUTOCOMPLETE_ENGINE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHGlihCSFZyAyIKgcUGwrsIJWKRdw-25
"""

!pip install datasets tensorflow

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import ReduceLROnPlateau
from datasets import load_dataset
import pickle
import re

dataset = load_dataset("wikitext", "wikitext-2-raw-v1")
train_text = " ".join(dataset["train"]["text"])

def clean_text(text):
    text = text.lower()
    text = re.sub(r"=+.*?=+", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

cleaned_text = clean_text(train_text)

VOCAB_SIZE = 12000

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts([cleaned_text])

total_words = min(VOCAB_SIZE, len(tokenizer.word_index) + 1)
print("Vocabulary Size:", total_words)

SEQ_LEN = 30

token_list = tokenizer.texts_to_sequences([cleaned_text])[0]

sequences = []
for i in range(SEQ_LEN, len(token_list)):
    sequences.append(token_list[i-SEQ_LEN:i+1])

sequences = np.array(sequences)

X = sequences[:, :-1]
y = sequences[:, -1]

print("X shape:", X.shape)

EMBED_DIM = 150
LSTM_UNITS = 256

model = Sequential([
    Embedding(total_words, EMBED_DIM, input_length=SEQ_LEN),
    LSTM(LSTM_UNITS, return_sequences=True),
    Dropout(0.3),
    LSTM(LSTM_UNITS),
    Dropout(0.3),
    Dense(total_words, activation='softmax')
])

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy']
)

model.summary()

lr_scheduler = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=2,
    verbose=1
)

history = model.fit(
    X, y,
    epochs=15,
    batch_size=128,
    validation_split=0.1,
    callbacks=[lr_scheduler]
)

model.save("autocomplete_lstm_fixed.h5")

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

def top_k_sampling(predictions, k=20, temperature=1.0):
    predictions = np.log(predictions + 1e-10) / temperature
    exp_preds = np.exp(predictions)
    predictions = exp_preds / np.sum(exp_preds)

    indices = np.argsort(predictions)[-k:]
    probs = predictions[indices]
    probs = probs / np.sum(probs)

    return np.random.choice(indices, p=probs)

def generate_text(seed_text, max_tokens=20, temperature=1.0, k=20):

    oov_index = tokenizer.word_index["<OOV>"]

    for _ in range(max_tokens):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=SEQ_LEN, padding='pre')

        predictions = model.predict(token_list, verbose=0)[0]

        # Remove OOV from prediction
        if oov_index < len(predictions):
            predictions[oov_index] = 0

        predictions = predictions / np.sum(predictions)

        predicted_index = top_k_sampling(predictions, k=k, temperature=temperature)

        output_word = tokenizer.index_word.get(predicted_index, "")

        if output_word == "":
            break

        seed_text += " " + output_word

        if output_word.endswith("."):
            break

    return seed_text

seed = "we have to"

print("Temp 0.7:")
print(generate_text(seed, temperature=0.7))

print("\nTemp 1.0:")
print(generate_text(seed, temperature=1.0))

print("\nTemp 1.3:")
print(generate_text(seed, temperature=1.3))

from google.colab import files

files.download("autocomplete_lstm_fixed.h5")
files.download("tokenizer.pkl")